version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5173:5173"
    volumes:
      - ./data:/app/data
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - llama
      - coquitts
      - facefusion
      - wav2lip
    env_file: .env
    restart: unless-stopped

  llama:
    build:
      context: .
      dockerfile: ./docker/llama.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./llama/models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  coquitts:
    build:
      context: .
      dockerfile: ./docker/coquitts.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  facefusion:
    build:
      context: .
      dockerfile: ./docker/facefusion.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8003:8003"
      - "7860:7860"  # WebUI用
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  wav2lip:
    build:
      context: .
      dockerfile: ./docker/wav2lip.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8004:8004"
    volumes:
      - ./data:/workspace/data
      - ./wav2lip/models:/workspace/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped 