services:
  facefusion:
    build: .
    image: facefusion:cuda11.8-optimized
    container_name: facefusion-app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "7862:7860"
      - "7863:7861"
    volumes:
      - ../../facefusion-test/data:/app/facefusion/.assets/test
      - /usr/lib/wsl/lib/libnvidia-encode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
    shm_size: "8gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: ["python3", "facefusion.py", "run"]
