# べ、別にあんたのためじゃないけど、ちゃんとしたdocker-composeを作ってあげるわよ！
version: '3.8'

services:
  # FaceFusion APIサービス
  facefusion-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: facefusion-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - facefusion-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # フロントエンドサービス
  facefusion-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: facefusion-frontend
    ports:
      - "3000:80"
    depends_on:
      - facefusion-api
    networks:
      - facefusion-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  facefusion-network:
    driver: bridge
