# べ、別にあんたのためじゃないけど、ちゃんとしたdocker-composeを作ってあげるわよ！
version: '3.8'

services:
  # FaceFusion API サービス
  facefusion-api:
    build: .
    container_name: facefusion-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./api/static/uploads:/app/api/static/uploads
      - ./api/static/outputs:/app/api/static/outputs
      - ./logs:/app/logs
      - facefusion-models:/app/facefusion/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - OMP_NUM_THREADS=1
      - FACEFUSION_PATH=/app/facefusion
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - facefusion-network

  # FaceFusion Frontend サービス
  facefusion-frontend:
    build: 
      context: ./facefusion-frontend
      dockerfile: Dockerfile
    container_name: facefusion-frontend
    ports:
      - "3000:3000"
    depends_on:
      - facefusion-api
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - facefusion-network

volumes:
  facefusion-models:

networks:
  facefusion-network:
    driver: bridge
